swagger: '2.0'
info:
  description: Bank API documentation for the transactions
  version: 1.0.0
  title: Argent Bank transactions API doc
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /v1
tags:
  - name: transactions
    description: Operations to manage transactions
schemes:
  - https
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - transactions
      summary: User Transactions API
      description: API for fetching all user transactions
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Transaction not found
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - transactions
      summary: Create a new transaction
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT Token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDescription'
      responses:
        '201':
          description: Successfull Operation
        '400':
          description: Invalid Transaction Description supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - transactions
      summary: User unique transaction
      description: Get transaction infos
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT Token
          required: true
          type: string
      responses:
        '200':
          description: Successfull Operation
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Transaction Description supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
    put:
      security:
        - Bearer: []
      tags:
        - transactions
      summary: Edit transaction
      description: Update transaction's description
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT Token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDescription'
      responses:
        '200':
          description: Successfull Operation
        '400':
          description: Invalid Transaction Description supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: transaction ID
      created:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: account balance after transaction
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: user's notes for transaction
  TransactionDescription:
    type: object
    properties:
      category:
        type: string
        description: transaction's category
      note:
        type: string
        description: user's notes for transaction
